### ISSUE TITLE
Potential variable name bug - freemuxlet.nf: grouplist_name

### ISSUE THREAD

**Issue by bednarsky** [theislab/hadge#22]
Dear hadge team, 

thanks for your amazing work, the pipeline seems incredibly useful! 

# My process to run hadge
I am trying to run it in the genetic mode (reference-free) in multi-sample mode, providing a sample_sheet that matches the example you recently provided. I cloned the repo and run it with this command `nextflow run main.nf -c ~/path/to/config -profile cluster`. 

Note: also this error is shown, but does not kill the pipeline: `unknown recognition error type: groovyjarjarantlr4.v4.runtime.LexerNoViableAltException`

# Potential bug
The pipeline fails with the error:
> Caused by:
> No such variable: grouplist_name -- Check script './modules/././gene_demulti/freemuxlet.nf' at line 71

&rarr; in this file once a variable `grouplist_name` is used, but above the variable is always called `grouplist`. I changed it in the source code pipeline source code and it seems to work (until the next error - I will write [another issue](https://github.com/theislab/hadge/issues/23#issue-1977336748))

Is this a bug, or is my error coming from something I did wrong?

**Comment by wxicu** [comment]
hey, thanks for pointing this out. We already noticed this bug and @mari-ga already fix it in her fork. You are totally right. We will try to merge her PR asap.

**Comment by bednarsky** [comment]
Amazing, thanks for the fast response!

**Comment by wxicu** [comment]
This is resolved in #20
