### ISSUE TITLE
Error demuxlet: work-dir=null, Path value cannot be null

### ISSUE THREAD

**Issue by bednarsky** [theislab/hadge#23]
Dear hadge team, 

thanks for your amazing work, the pipeline seems incredibly useful! 

# My process to run hadge
I am trying to run it in the genetic mode (reference-free) in multi-sample mode, providing a sample_sheet that matches the example you recently provided. I cloned the repo and run it with this command `nextflow run main.nf -c ~/path/to/config -profile cluster`.  The config file is in here: [hadge_bug_help.zip](https://github.com/theislab/hadge/files/13256741/hadge_bug_help.zip).

# Where my pipeline run fails
I am sorry if this is a basic bug but I am new to nextflow and couldn't figure out a solution myself. 

Error from .nextflow.log:
> task: name=run_multi:gene_demultiplexing:demultiplex_demuxlet:demuxlet (1); work-dir=null
> error [nextflow.exception.ProcessUnrecoverableException]: Path value cannot be null

The full nextflow_log file is in the [hadge_bug_help.zip](https://github.com/theislab/hadge/files/13256741/hadge_bug_help.zip) already given above. 

Note: I slightly adapted the pipeline to get this far, see [other issue](https://github.com/theislab/hadge/issues/22#issue-1977328224)

**Comment by wxicu** [comment]
Hey @bednarsky thanks for using hadge! I guess you checked the [example sheet](https://github.com/theislab/hadge/blob/main/multi_sample_input.csv) already. So for the demuxlet, I think the problem might be that it is required to have the donor genotypes of the cell mixtures, which is `params.vcf_donor`. If this is not available and the value is `None`, demuxlet will fail. In this case, please try freemuxlet instead.
I also noticed that you try to run souporcell. Please be aware that souporcell is only available in singularity container, so please install the singularity on your HPC first.

**Comment by bednarsky** [comment]
Thank you for the fast response!

**Comment by wxicu** [comment]
Please feel free to reopen this issue if you are still running into issues and we would be happy to help troubleshoot further.
