### ISSUE TITLE
Error: run_multi:gene_demultiplexing:summary (1); work-dir=null: Not a valid path value: 'None'

### ISSUE THREAD

**Issue by bednarsky** [theislab/hadge#31]
Dear hadge team, 

after all individual process have finished, my pipeline run dies at the summary stage with this error (from hadge/.nextflow.log):
> Nov-24 15:47:41.094 [Actor Thread 4965] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
>   task: name=run_multi:gene_demultiplexing:summary (1); work-dir=null
>   error [nextflow.exception.ProcessUnrecoverableException]: Not a valid path value: 'None'
> Nov-24 15:47:41.528 [Actor Thread 4965] ERROR nextflow.processor.TaskProcessor - Error executing process > 'run_multi:gene_demultiplexing:summary (1)'
> 
> Caused by:
>   Not a valid path value: 'None'

This is my config file: 
[nextflow.config.zip](https://github.com/theislab/hadge/files/13473632/nextflow.config.zip)

My sample sheet is modelled after the example you are giving in the repo. 
Couldn't quickly figure out what's going on. No work-dir is created at all, thus little info about specific command that fails. 

Thanks again for all your help! Now I should be done soon!

All the very best, 
Raphael

**Comment by wxicu** [comment]
Hey Raphael,
I guess this is because either hto or rna matrix is not given; ofc this is a bug. I fixed this in the PR #32 . Hope it works now!



Xichen
