### ISSUE TITLE
Error: HADGE:run_multi:gene_demultiplexing:variant_cellSNP:cellSNP (1): Not a valid path value: 'None'

### ISSUE THREAD

**Issue by zimea** [theislab/hadge#44]
Dear hadge team, 

I want to use hadge for genetic-based donor demultiplexing and first run the pipeline using the test data.
For that, I run the download_data.sh script in test_data and did not replace the previously existing files.

Running `nextflow run main.nf -profile conda_singularity --mode genetic` results in the Error:

ERROR ~ Error executing process > 'HADGE:run_multi:gene_demultiplexing:variant_cellSNP:cellSNP (1)'

Caused by:
  Not a valid path value: 'None'

Is there sth that I could do differently?Many thanks in advance!

All the best,
Lea

**Comment by wxicu** [comment]
Hi Lea,
to run with the test data, please also specify the test config in the `config` parameter, i.e. `nextflow run main.nf -profile conda_singularity,test --mode genetic`
If the error still exists, please check whether the bam file with its index file and barcodes have been successfully downloaded. Sometimes gdown blocks the file due to frequent access.


Best wishes
Xichen

**Comment by zimea** [comment]
Hi Xichen,
thanks for the reply - you're right, that fixed the issue.

Now the pipeline runs some of the tools, including souporcell, demuxlet & freemuxlet, but breaks during the scSplit analysis with the error:

ERROR ~ Error executing process > 'HADGE:run_multi:gene_demultiplexing:demultiplex_scSplit:scSplit (hadge_process)'

Caused by:
  Process `HADGE:run_multi:gene_demultiplexing:demultiplex_scSplit:scSplit (hadge_process)` terminated with an error exit status (143)

Command executed:

  git clone https://github.com/jon-xu/scSplit
         mkdir scsplit_hadge_process
         mkdir scsplit_hadge_process/scsplit_out
         touch scsplit_hadge_process/params.csv
         echo -e "Argument,Value
  vcf,filtered_sorted_total_chroms.vcf
  bam,hadge_process__filtered_bam_file.bam
  barcode,barcodes.tsv
  common_data,/lustre/groups/ml01/workspace/lea.zimmermann/projects/hadge/hadge/test_data/common_variants_hg19_list.vcf
  num,2
  sub,no_sub
  ems,30
  dbl,None
  vcf_known_data,/projects/hadge/hadge/test_data/jurkat_293t_exons_only.vcf.withAF.vcf" >> scsplit_hadge_process/params.csv

         python scSplit/scSplit count -v filtered_sorted_total_chroms.vcf -i hadge_process__filtered_bam_file.bam -b barcodes.tsv --com /projects/hadge/hadge/test_data/common_variants_hg19_list.vcf -r ref_filtered.csv -a alt_filtered.csv --out scsplit_hadge_process/scsplit_out
         python scSplit/scSplit run -r scsplit_hadge_process/scsplit_out/ref_filtered.csv -a scsplit_hadge_process/scsplit_out/alt_filtered.csv -n 2  --ems 30  --vcf /projects/hadge/hadge/test_data/jurkat_293t_exons_only.vcf.withAF.vcf --out scsplit_hadge_process/scsplit_out

         if [[ "False" != "False" ]]
         then
             python scSplit/scSplit genotype -r scsplit_hadge_process/scsplit_out/ref_filtered.csv -a scsplit_hadge_process/scsplit_out/alt_filtered.csv -p scsplit_hadge_process/scsplit_out/scSplit_P_s_c.csv --out scsplit_hadge_process/scsplit_out
         fi

Command exit status:
  143

Command output:
  (empty)

Command error:
  Cloning into 'scSplit'...
  .command.sh: line 18: 3689175 Terminated              python scSplit/scSplit run -r scsplit_hadge_process/scsplit_out/ref_filtered.csv -a scsplit_hadge_process/scsplit_out/alt_filtered.csv -n 2 --ems 30 --vcf /lustre/groups/ml01/workspace/lea.zimmermann/projects/hadge/hadge/test_data/jurkat_293t_exons_only.vcf.withAF.vcf --out scsplit_hadge_process/scsplit_out

So far, I couldn't find information about the cause of the error in the log/err files.
Have you seen a similar error before and might have an idea, how to find the error?
Thanks again for your help!

Best wishes,
Lea

**Comment by wxicu** [comment]
I guess this is caused by out-of-memory issue but also not 100% sure. Sometimes you can find a more helpful error log in the work directory of this process, like `work/ab/afurbefn/.command.err` or `.command.log`. If this doesnt tell you more about the error code, then please run scsplit with more memory resource since scsplit requires much meory

**Comment by zimea** [comment]
The files unfortunately don't contain more information. I'll try running with more memory.
Thanks a lot!

**Comment by zimea** [comment]
Hi Xichen,

thanks for the help so far! Could you also help with another question?
I still try to get the pipeline to run on the cluster 

`nextflow run ../hadge/main.nf -profile conda_singularity,test,cluster --mode genetic`

and get the error: 

ERROR ~ Error executing process > 'HADGE:run_multi:gene_demultiplexing:demultiplex_vireo:vireo (hadge_process)'

Caused by:
  Process `HADGE:run_multi:gene_demultiplexing:demultiplex_vireo:vireo (hadge_process)` terminated with an error exit status (127)

Command executed:

  bcftools view /lustre/groups/ml01/workspace/lea.zimmermann/projects/hadge/hadge/test_data/jurkat_293t_exons_only.vcf.withAF.vcf | awk '{gsub(/^chr/,""); print}' | awk '{gsub(/ID=chr/,"ID="); print}' > no_prefix_chr.vcf
         mkdir vireo_hadge_process
         mkdir vireo_hadge_process/vireo_out
         touch vireo_hadge_process/params.csv
         echo -e "Argument,Value
  cell_data,cellSNP_out
  n_donor,2
  donor_data,/lustre/groups/ml01/workspace/lea.zimmermann/projects/hadge/hadge/test_data/jurkat_293t_exons_only.vcf.withAF.vcf
  genoTag,GT
  noDoublet,False
  nInit,50
  extraDonor,0
  extraDonorMode,distance
  learnGT,False
  ASEmode,False
  noPlot,False
  randSeed,None
  cellRange,all
  callAmbientRNAs,False
  nproc,2" >> vireo_hadge_process/params.csv

         vireo -c cellSNP_out -N 2 -d no_prefix_chr.vcf --genoTag GT  --nInit 50 --extraDonor 0                    --nproc 2 -o vireo_hadge_process/vireo_out

         if ([ "/lustre/groups/ml01/workspace/lea.zimmermann/projects/hadge/hadge/test_data/jurkat_293t_exons_only.vcf.withAF.vcf" = "Donor file is not given" ]); then
             if ([ "False" = "True" ] || [ "False" = "vireo" ]); then
                 GTbarcode -i vireo_hadge_process/vireo_out/GT_donors.vireo.vcf.gz -o vireo_hadge_process/vireo_out/filtered_variants.tsv None
             fi
         fi

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: bcftools: command not found
  .command.sh: line 23: vireo: command not found

Is there something that I need to install previously to running the pipeline?
Many thanks for your help!

Best,
Lea

**Comment by wxicu** [comment]
Hi Lea,
it is weird LOL. Conda environment should be installed and activated automatically with `conda "aksarkar::vireosnp bioconda::bcftools"` in the script. I guess the reason for that the previous pipeline run was interrupted by scSplit, whereas conda environment for vireo and bcftools was still being installed. You can delete the whole folder `work/conda` (easier solution) or only the folder responsible for the vireo environment. Hope this will help!


Best wishes,
Xichen

**Comment by bednarsky** [comment]
Probably this is already fixed, but I had the same issue and could fix it by adding conda params to the cluster setup, like
```nextflow
cluster {
    conda.enabled          = true
    conda.cacheDir         = '../../miniconda_link/hadge_envs'
    process {
        ...
    }
}
```
Not sure if both are necessary
