### ISSUE TITLE
souporcell_pipeline.py: command not found

### ISSUE THREAD

**Issue by bednarsky** [theislab/hadge#53]
Hi again! Sorry if I cause a lot of errors, really appreciate all your help!

> Caused by:
>   Process `HADGE:run_multi:gene_demultiplexing:demultiplex_souporcell:souporcell (sampleID)` terminated with an error exit status (127)
> 
> Command executed:
> 
>          mkdir souporcell_sampleID
>          mkdir souporcell_sampleID/souporcell_out
>          touch souporcell_sampleID/params.csv
>          echo -e "Argument,Value
>   bamfile,sampleID__filtered_bam_file.bam
>   barcode,barcodes.tsv.gz
>   fasta,genome.fa
>   threads,5
>   clusters,2
>   ploidy,2
>   min_alt,10
>   min_ref,10
>   max_loci,2048
>   restarts,None
>   common_variant,No common variants are given.
>   known_genotype,/path/to/project/results/demultiplexing/split_wgs_vcf/project.sampleID.vcf
>   known_genotype_sample,No known sample names are given.
>   skip_remap,True
>   ignore,False " >> souporcell_sampleID/params.csv
> 
>          souporcell_pipeline.py --threads 32 -i sampleID__filtered_bam_file.bam -b barcodes.tsv.gz -f genome.fa -t 5 -k 2 --ploidy 2 --min_alt 10 --min_ref 10 --max_loci 2048               --known_genotypes unzipped.vcf  --skip_remap True  -o souporcell_sampleID/souporcell_out
> 
> Command exit status:
>   127
> 
> Command output:
>   (empty)
> 
> Command error:
>   .command.sh: line 26: souporcell_pipeline.py: command not found

Could this be due to the corrupted singularity image (https://github.com/theislab/hadge/issues/49)? I am cleaning my cache now and trying again

**Comment by wxicu** [comment]
How did you call the pipeline? Use which profile then?

**Comment by bednarsky** [comment]
> How did you call the pipeline? Use which profile then?

I use the flag `-profile cluster` in my `nextflow run ..` call

Should I also put `singularity.enabled    = true` into the cluster profile, then?

**Comment by wxicu** [comment]
yes exactly, you can also do thay by using the existing profiles `--profile cluster,conda_singularity`. The second profile enables both conda and souporcell (check the latest [doc](https://hadge.readthedocs.io/en/latest/index.html), e.g. section "Quick start")

**Comment by wxicu** [comment]
> > How did you call the pipeline? Use which profile then?
> 
> I use the flag `-profile cluster` in my `nextflow run ..` call
> 
> Should I also put `singularity.enabled = true` into the cluster profile, then?

yes exactly, you can also do thay by using the existing profiles --profile cluster,conda_singularity. The second profile enables both conda and souporcell (check the latest [doc](https://hadge.readthedocs.io/en/latest/index.html), e.g. section "Quick start")

**Comment by bednarsky** [comment]
Ah sorry, overlooked that. Will try! Thanks for the quick help, really appreciate it!

**Comment by bednarsky** [comment]
Worked, thanks
