### ISSUE TITLE
elaboration on sample vs donor

### ISSUE THREAD

**Issue by julicudini** [theislab/hadge#54]
Hello! Thanks for the tool. 

I was wondering if you elaborate on your notation a bit in the documentation. You say the minimum input for running demuxlet is a genotype reference per sample - does 'sample' here mean per individual in a pooled run? Meaning this would be say 8 vcfs for a pool of 8 donors? Or is the sample the pooled run itself, meaning you would have one cohort level vcf with all of the donors that are in that pool in the vcf. Later you specify that to run demuxlet you would include the parameter `--vcf_donor`, and again it is unclear what the difference between donor and sample is here, and if this is meant to be one vcf with one donor or one vcf with many donors in that sample? In the original implementation of demuxlet, one can specify the ids of the donors that are in that sample such that you can provide a cohort level vcf that has more than just the donors in that sample in it. Is this possible here? Or does the vcf have to only include the donors that are in that sample? Also, how does `vcf_mixed` differ in this context?

Thank you very much!

**Comment by wxicu** [comment]
Hi,

> does 'sample' here mean per individual in a pooled run?

Yes in this context, we refer samples refer to the individual in a pooled run. This is also what we mean by "donor".

> Meaning this would be say 8 vcfs for a pool of 8 donors? Or is the sample the pooled run itself, meaning you would have one cohort level vcf with all of the donors that are in that pool in the vcf. Later you specify that to run demuxlet you would include the parameter --vcf_donor, and again it is unclear what the difference between donor and sample is here, and if this is meant to be one vcf with one donor or one vcf with many donors in that sample?

The donor and sample is the same thing there. But for clarification now I will use donor for consistency. `--vcf_donor` is the minimal input of demuxlet you mentioned. It expects only one vcf, which contains the genotype of all donors in that pool, with each donor corresponding to one column. An example would be like:
#CHROM     POS ID     REF     ALT     QUAL     FILTER     INFO     FORMAT     DONOR1     DONOR2 ...
I think this is also what you mean by "one cohort level vcf".

> In the original implementation of demuxlet, one can specify the ids of the donors that are in that sample such that you can provide a cohort level vcf that has more than just the donors in that sample in it. Is this possible here? Or does the vcf have to only include the donors that are in that sample? 

This is also possible here. You just need to specify with the parameter `--sm` or `--sm-list` which is also used by demuxlet.

> Also, how does vcf_mixed differ in this context?

`vcf_mixed` is used by scSplit. According to scSplit, freebayes is required to call SNVs from the mixed sample BAM file. So bascially it provides SNP candidates in the pooled sample, but not have to be in a per-donor level. An example would be like:
#CHROM     POS ID     REF     ALT     QUAL     FILTER     INFO     FORMAT     Pooled_Sample


I hope this explanation helps clarify the uses of these terms and file types. We are currently working on converting the pipeline to nf-core modules. We will also improve the documentation in the meantime. If you have further questions or need more details, feel free to ask!

**Comment by julicudini** [comment]
This was really helpful! Thank you :)
