### ISSUE TITLE
Add scverse support

### ISSUE THREAD

**Issue by Zethson** [theislab/hadge#6]
Ensure that every tool in our pipeline gets a process that can output an annotated AnnData object that makes sense. The AnnData object should contain the expression matrix in X and the donor assignment in obs. Other information such as ambient RNA, doublet detection etc should then be obs columns.

- [ ] Add a parameter to the overall pipeline such as `--generate-anndata` or so
- [ ] multiseq
- [ ] htodemux
- [ ] dropletutils
- [ ] solo
- [ ] hashsolo
- [ ] scsplit
- [ ] souporcell
- [ ] freemuxlet
- [ ] demuxlet
- [ ] vireo

**Comment by wxicu** [comment]
@mari-ga Could you please add the `generate-mudata` option? I hope I have already made a clear structure for that! Thank you.

**Comment by Zethson** [comment]
@wxicu can we close this?

**Comment by mari-ga** [comment]
Currently adding mudata support for hashing
