### ISSUE TITLE
Add some hashing tools

### ISSUE THREAD

**Issue by wxicu** [theislab/hadge#8]
Add other hashing tools in the workflow
- [x] Demuxmix
- [x] BFF
- [x] Other tools

**Comment by mari-ga** [comment]
Both Demuxmix and BFF - complete
Waiting for information about other necessary tools

**Comment by wxicu** [comment]
> Both Demuxmix and BFF - complete Waiting for information about other necessary tools

Thank you very much! Could you please make a pull request for that? It would be great!

**Comment by Zethson** [comment]
Uhm, can we close this one now?
